# Generated by Django 3.2.8 on 2022-05-14 09:11

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_work', models.CharField(db_index=True, max_length=255, verbose_name='Название подтемы')),
                ('name_topic', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255, verbose_name='Описание подтемы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Подтема',
                'verbose_name_plural': 'Подтемы',
            },
        ),
        migrations.CreateModel(
            name='TopicMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название Темы')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание темы')),
            ],
            options={
                'verbose_name': 'Тему',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание видео')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='введите URL (Video)')),
                ('topik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='topik.topic', verbose_name='Подтема')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание Файла')),
                ('file', models.FileField(upload_to='', verbose_name='файл')),
                ('topik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='topik.topic', verbose_name='Темы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='ChoiceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicmain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choice_topic', to='topik.topicmain', verbose_name='Темы')),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics_choice', to='topik.topic', verbose_name='Подтема')),
            ],
            options={
                'verbose_name': 'Выберите тему',
                'verbose_name_plural': 'Выберите темы',
            },
        ),
    ]
