# Generated by Django 3.2.8 on 2022-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published_date',
            field=models.DateTimeField(blank=True, verbose_name='Завершение курса'),
        ),
    ]
