# Generated by Django 3.2.8 on 2022-05-15 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_сhoicequestion_test'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_alter_applicationtoadmin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Пройден'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='quiz_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.test', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
