# Generated by Django 3.2.8 on 2022-05-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_remove_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сhoicequestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicetest', to='test.test', verbose_name='Тест'),
        ),
    ]
